import type { Metadata } from "next";
import { Manrope, Raleway} from "next/font/google";
import '@mantine/core/styles.css';

import {
    mantineHtmlProps,
    MantineProvider
} from "@mantine/core";
import AppLayout from "@/app/layout_app";
import "./globals.css";
import {theme} from "@/app/assets/theme";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ['cyrillic'],
    display: 'swap',
});


const raleway = Raleway({

  variable: "--font-raleway",
  subsets: ['cyrillic', 'latin'],
    display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru"  {...mantineHtmlProps} className={`${raleway.variable} ${manrope.variable}`}>

      <body
        className={`antialiased`}
      >
        <MantineProvider theme={theme} defaultColorScheme={"light"} forceColorScheme={"light"}>
            <AppLayout>{children}</AppLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
